// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://sdprrmzpdmbhtwseszpm.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcHJybXpwZG1iaHR3c2VzenBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MDIxNjEsImV4cCI6MjA0OTA3ODE2MX0.-CkRXLbZq7g-HdbR9rXpBJ4rz4M9DLkpEopEnyv8Mu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);