// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://smsffnbfcpybezaljgmd.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtc2ZmbmJmY3B5YmV6YWxqZ21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MjY0ODEsImV4cCI6MjEwMDUwMjQ4MX0.MV8Z5BSzwyUvpLNpZoQje1kEd2Y2f2lC5hFHg-BEETk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);